[package]
name = "logparse"
version = "0.1.0"
edition = "2021"
rust-version = "1.82.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
csv = "1.3.0"
thiserror = "1.0.67"

[workspace]
members = ["src-tauri"]
