[package]
name = "logparse"
version = "0.1.0"
edition = "2021"
rust-version = "1.82.0"

[[bin]]
name = "logparse"
path = "src-tauri/main.rs" # Path to the binary file for the application

[workspace]
default-members = ["src-tauri"]
members = ["src-tauri"]
