CREATE TABLE logs (
	id SERIAL PRIMARY KEY
);

CREATE TABLE events (
	id SERIAL PRIMARY KEY,
	`type` VARCHAR(255) NOT NULL,
	`timestamp` TIMESTAMP NOT NULL,
	fields JSONB DEFAULT '{}',
	fk_log_id SERIAL NOT NULL REFERENCES logs(id) ON DELETE CASCADE
);
