CREATE TABLE logs (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
);

CREATE TABLE events (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	`timestamp` TIMESTAMP NOT NULL,
	fields JSON DEFAULT '{}',
	fk_log_id INTEGER NOT NULL REFERENCES logs(id) ON DELETE CASCADE
);
